# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "quenty/rojo@7.2.1-quenty-npm-canary.5"
selene = "kampfkarren/selene@0.21.0"
wally = "UpliftGames/wally@0.3.1"
