[docusaurus]
title = "NeoHotbar"
tagline = "A modern, flexible hotbar for Roblox"
url = "https://avafe.me"
favicon = "/img/favicon.svg"

[home]
enabled = true

[[home.features]]
title = "Easy to Use"
description = "Getting started with NeoHotbar is easy and customization is too."

[[home.features]]
title = "Customizable"
description = "NeoHotbar features custom buttons, full UI overriding and more."

[[home.features]]
title = "Compatible"
description = "NeoHotbar supports all devices, utilizing all Tool features, improving upon many of them."

[footer]
style = "dark"
copyright = "Copyright Â© 2023 Avafe. Built with Moonwave and Docusaurus"